### ISSUE TITLE
Hello. Opening this request to participate in the SOSC

### ISSUE THREAD

**Issue by smilinrobin** [SeleniumHQ/sosc#39]
Hello. I would like to participate in the SOSC and contribute to the community. 
Thanks.

**Comment by diemol** [comment]
You can find the instructions at https://www.selenium.dev/blog/2023/selenium-open-space-conference/.

**Comment by maaretp** [comment]
Welcome. We would like to know which ones of the four sections fit your schedules/timezones to include that on the page:
[ ]  Segment 1 7am-1pm UTC
[ ]  Segment 2 1pm-7pm UTC
[ ] Segment 3 7pm-1am UTC
[ ] Segment 4 1am-7am UTC

Also, do you have any topics you would want to host sessions on? You can decide on those in the moment, but if you already have a conversation topic in mind, it usually helps people choose they will join as well.

**Comment by maaretp** [comment]
> You can find the instructions at https://www.selenium.dev/blog/2023/selenium-open-space-conference/.

Diego, we added enroll by issue ticket so please don't close before we add this.

**Comment by maaretp** [comment]
https://github.com/SeleniumHQ/sosc/pull/40/ merged, times missing from the information.

**Comment by smilinrobin** [comment]
> Welcome. We would like to know which ones of the four sections fit your schedules/timezones to include that on the page: [ ] Segment 1 7am-1pm UTC [ ] Segment 2 1pm-7pm UTC [ ] Segment 3 7pm-1am UTC [ ] Segment 4 1am-7am UTC
> 
> Also, do you have any topics you would want to host sessions on? You can decide on those in the moment, but if you already have a conversation topic in mind, it usually helps people choose they will join as well.

Sure thing @maaretp . I would like to join  Segment 1 7am-1pm UTC. Also, I can host sessions on the below topics:

- Selenium for SAAS applications (Salesforce/Oracle etc.)
- Future of Test Automation (with a pinch of AI)
- Getting started with Selenium (absolute beginner's mindset)

**Comment by maaretp** [comment]
Added https://github.com/SeleniumHQ/sosc/pull/41
