### ISSUE TITLE
This is a Test Issue

### ISSUE THREAD

**Issue by AniDob** [SeleniumHQ/sosc#70]
Hello. I would like to participate in the SOSC and contribute to the community.
Thanks.

**Comment by maaretp** [comment]
Would you tell your name to add on the page - you are free to join us also without that at this point, but we would be happy to document you on the event page.

**Comment by Sharath-art** [comment]
Hello. I would like to participate in the SOSC and contribute to the community.
Thanks.

**Comment by maaretp** [comment]
2023 event closed.
