### ISSUE TITLE
Registeration request to attend ( building selenium ecosystem framework by mohab mohie )

### ISSUE THREAD

**Issue by abdulrhmanAlfiky** [SeleniumHQ/sosc#72]
Please accept my registration to attend this event 

my name is abdulrhman alfiky 
QA & Test automation engineer at vodafone egypt

**Comment by maaretp** [comment]
You are welcome to join the event, I will add you to the page.

**Comment by maaretp** [comment]
https://github.com/SeleniumHQ/sosc/pull/73
